In [4]:
import numpy as np

class HopfieldNetwork:
    def __init__(self, size):
        self.size = size
        self.weights = np.zeros((size, size))

    def train(self, patterns):
        """Train the network with given patterns."""
        for p in patterns:
            p = p.reshape(-1, 1)  # Ensure column vector
            self.weights += p @ p.T
        np.fill_diagonal(self.weights, 0)  # No self-connections
        self.weights /= len(patterns)  # Normalize by the number of patterns

    def recall(self, pattern, steps=5):
        """Recall a pattern from memory."""
        recalled_pattern = pattern.copy()
        for _ in range(steps):
            for i in range(self.size):
                # Asynchronous update
                activation = np.dot(self.weights[i], recalled_pattern)
                recalled_pattern[i] = 1 if activation >= 0 else -1
        return recalled_pattern

# Create a 10x10 Hopfield network
size = 10 * 10
network = HopfieldNetwork(size)

# Define patterns (as 10x10 binary matrices)
patterns = [
    np.random.choice([-1, 1], size=(size,)),
    np.random.choice([-1, 1], size=(size,))
]

# Train the network
network.train(patterns)

# Test recall
test_pattern = patterns[0].copy()
test_pattern[:10] = -test_pattern[:10]  # Add some noise
recalled_pattern = network.recall(test_pattern)

# Display results
print("Original Pattern:\n", patterns[0].reshape(10, 10))
print("Noisy Input Pattern:\n", test_pattern.reshape(10, 10))
print("Recalled Pattern:\n", recalled_pattern.reshape(10, 10))


Original Pattern:
 [[ 1 -1 -1 -1 -1  1  1  1  1 -1]
 [-1 -1  1  1  1  1 -1  1 -1  1]
 [ 1 -1 -1 -1  1 -1  1 -1 -1  1]
 [ 1  1  1 -1  1  1  1  1  1 -1]
 [ 1 -1  1 -1 -1  1  1  1  1 -1]
 [-1 -1 -1 -1  1 -1 -1  1  1 -1]
 [-1 -1 -1 -1 -1  1 -1  1 -1  1]
 [-1  1  1  1 -1 -1 -1  1  1  1]
 [ 1  1 -1 -1 -1 -1 -1 -1  1 -1]
 [-1 -1  1  1 -1  1 -1  1  1 -1]]
Noisy Input Pattern:
 [[-1  1  1  1  1 -1 -1 -1 -1  1]
 [-1 -1  1  1  1  1 -1  1 -1  1]
 [ 1 -1 -1 -1  1 -1  1 -1 -1  1]
 [ 1  1  1 -1  1  1  1  1  1 -1]
 [ 1 -1  1 -1 -1  1  1  1  1 -1]
 [-1 -1 -1 -1  1 -1 -1  1  1 -1]
 [-1 -1 -1 -1 -1  1 -1  1 -1  1]
 [-1  1  1  1 -1 -1 -1  1  1  1]
 [ 1  1 -1 -1 -1 -1 -1 -1  1 -1]
 [-1 -1  1  1 -1  1 -1  1  1 -1]]
Recalled Pattern:
 [[ 1 -1 -1 -1 -1  1  1  1  1 -1]
 [-1 -1  1  1  1  1 -1  1 -1  1]
 [ 1 -1 -1 -1  1 -1  1 -1 -1  1]
 [ 1  1  1 -1  1  1  1  1  1 -1]
 [ 1 -1  1 -1 -1  1  1  1  1 -1]
 [-1 -1 -1 -1  1 -1 -1  1  1 -1]
 [-1 -1 -1 -1 -1  1 -1  1 -1  1]
 [-1  1  1  1 -1 -1 -1  1  1  1]
 [ 1  1 -1 -1 